/**
 * Workspace Business module — re-exports API helpers from the shared client.
 * Prefer importing from here in `app/workspaces/**` to keep a single integration surface.
 */
export {
  acceptBusinessInvite,
  approveBusinessSpend,
  createBusinessCostCenter,
  createBusinessMember,
  createBusinessUnit,
  createBusinessVendor,
  createBusinessWorkspace,
  fetchBusinessCostCenters,
  fetchBusinessControlSummary,
  fetchBusinessDashboard,
  fetchBusinessInsights,
  fetchBusinessMemberInvites,
  fetchBusinessMembers,
  fetchBusinessRecommendations,
  fetchBusinessSignals,
  fetchBusinessSpends,
  fetchBusinessToday,
  fetchBusinessUnits,
  fetchBusinessVendors,
  fetchBusinessWorkspace,
  fetchBusinessWorkspaces,
  inviteBusinessMemberByEmail,
  rejectBusinessSpend,
  submitBusinessSpend,
  updateBusinessMember,
  type BusinessActivity,
  type BusinessControlSummary,
  type BusinessCostCenter,
  type BusinessDashboard,
  type BusinessInsights,
  type BusinessMember,
  type BusinessMemberInvite,
  type BusinessRecommendation,
  type BusinessSignal,
  type BusinessSpend,
  type BusinessToday,
  type BusinessUnit,
  type BusinessVendor,
  type BusinessWorkspace,
} from "@/lib/api/business";
